### PR TITLE
Add Online Mods Ping

### PR DESCRIPTION
**Pull request by sun3matthew**
I have no idea how if it works, I just looked at the discord api and pretended to know java script.
It finds the MODS role then filters out the online mods and pings them

### CODE REVIEW

**Comment by sun3matthew** [comment]
Maybe remove the online part? bc all the mods are either idle or on do not disturb

**Comment by ky28059** [comment]
Hmm, interesting, but it only works for a role specifically named 'MODS' and you could just ping that role anyways so idk

**Comment by sun3matthew** [comment]
It'll only ping ppl who are not offline

**Comment by ky28059** [comment]
You can use '<@' + member.id + '>' to actually send them a ping

**Pull request closed without merging**
